#---------------------------------------------INDEX
index:
    path: /
    controller: App\Controller\index\LoginController::loginPage
index2:
    path: /index
    controller: App\Controller\index\LoginController::loginPage
index3:
    path: /login
    controller: App\Controller\index\LoginController::loginPage
#------------------------------------------------ADMINISTRATOR
adminDashboard:
    path: administrator/dashboard
    controller: App\Controller\Administrator\DashboardController::dashboard
adminRooms:
    path: administrator/administration/rooms
    controller: App\Controller\Administrator\RoomController::listRooms
